name = "Created Gravy"
author = "wozeparrot"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f54406225206a738165afe4f8632b7a69d4e938cfaf9248260a6adaac5bc3c45"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
